Add chapter "What is NEAT"
IDPA16/Docs pull request #22
Opened 2017-01-05 18:09 UTC by STJEREM

2017-01-05 19:46 UTC, janhohenheim approved these changes

2017-01-09 16:30 UTC, janhohenheim requested changes

2017-01-09 16:30 UTC, SirRade commented on sections/what is neat.tex
> +It proposes an elegant way to combine genetic algorithms with evolving topologies.
What is a topology?

2017-01-09 16:30 UTC, SirRade commented on sections/what is neat/topology.tex
> +NEAT proposes a technique to evolve the topology over time which allows the network to be better structured for a specific task then a configuration with hyper parameters.
How?

2017-01-09 16:34 UTC, STJEREM commented on sections/what is neat.tex
> +It proposes an elegant way to combine genetic algorithms with evolving topologies.
I think we should add this to the chapter "Introduction to neural networks"

2017-01-09 16:35 UTC, STJEREM commented on sections/what is neat/topology.tex
> +NEAT proposes a technique to evolve the topology over time which allows the network to be better structured for a specific task then a configuration with hyper parameters.
Explained in the "Speciation" subsection

2017-01-09 17:34 UTC, janhohenheim approved these changes

2017-01-09 17:34 UTC, merged